language: android
jdk: oraclejdk7

android:
  components:

    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24

    - sys-img-armeabi-v7a-android-24

script: ./gradlew clean build