language: android
jdk: oraclejdk8

android:
  components:
    # The BuildTools version used by your project
    - build-tools-24.0.0

    # The SDK version used to compile your project
    - android-24

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
  licenses:
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+

script: ./gradlew clean build

after_failure: "cat /home/travis/build/toni-rajkovski/transport-app-demo/app/build/outputs/lint-results.xml"